'use strict';

//Original version of this file was auto-generated by express-generator.

const app = require('./app');
const debug = require('debug')('meanwifi:server');
const http = require('http');
const runtime = require('./runtime');

runtime.printOptions();

app.ready
  .then((result) => {
    debug(result);

    const port = runtime.options.port;
    app.set('port', port);

    const server = http.createServer(app);
    server.listen(port);

    server.on('error', (error) => {
      if (error.syscall !== 'listen') {
        throw error;
      }

      let bind = typeof port === 'string' ? 'Pipe ' + port : 'Port ' + port;

      // handle specific listen errors with friendly messages
      switch (error.code) {
        case 'EACCES':
          console.error(bind + ' requires elevated privileges');
          process.exit(1);
          break;
        case 'EADDRINUSE':
          console.error(bind + ' is already in use');
          process.exit(1);
          break;
        default:
          throw error;
      }
    });

    server.on('listening', () => {
      let addr = server.address();
      let bind =
        typeof addr === 'string' ? 'pipe ' + addr : 'port ' + addr.port;
      debug('Listening on ' + bind);
    });
  })
  .catch((error) => {
    console.error(error);
    app.dbConnection.close();
  });
